### ISSUE TITLE
How did you make the animated gifs on your blog with the keystrokes in the lower right?

### ISSUE THREAD

**Issue by sdondley** [SidOfc/dotfiles#4] opened 2020-07-18 19:16 UTC
Was just thinking about my need for this yesterday and well, your blog appeared before me.

https://sidneyliebrand.io/blog/how-fzf-and-ripgrep-improved-my-workflow

Thanks. And sorry for polluting your issue queue.

**Comment by SidOfc** [comment] 2020-07-19 17:45
Hi @sdondley,

No worries about the 'pollution', I created these gifs on a mac using [Screenflick](https://www.araelium.com/screenflick-mac-screen-recorder). What you see on my website however, is actually a webm or mp4 file because those tend to be smaller than gif, so if you plan on creating gifs and putting them on a website, I'd recommend converting them to [webm](https://sidneyliebrand.io/til/converting-gif-to-webm-using-ffmpeg) or [mp4](https://sidneyliebrand.io/til/converting-gif-to-web-safe-mp4-using-ffmpeg).

I'll close this assuming I answered your original question, if you've got more questions, you can find me on twitter [@scbydoooo](https://twitter.com/scbydoooo) :)

**Closed by SidOfc** 2020-07-19 17:45 UTC
Labels: question

**Comment by sdondley** [comment] 2020-07-19 18:48
Thanks!

Yes, I noticed that these were webm and mp4 format after I posted my question. I got curious and I did a little more research and found that gifs are actually larger than mp4s. I wrongly assumed that for small screen captures, where the most of the frames are the same, that gifs would be smaller (I'm obviously not knowledgeable about video compression). But I'm still curious and plan on using ffmpeg to see just how close small I can make a gif if the color palleted is reduced.

I also looked for an open source solution as well to do screen captures. One that I found, Kap, does not have a key press feature: https://github.com/wulkano/Kap. There is a plugin available for showing keys but it's very poorly executed. There is another project for displaying key presses: https://github.com/keycastr/keycastr. You can simply place this in the corner of the screen capture.

These solutions are not ideal, however. keycastr is buggy on my large monitor: https://github.com/keycastr/keycastr/issues/173

Probably more than you wanted to know. Just sharing this in case anyone else stumbles on it.

**Comment by SidOfc** [comment] 2020-07-20 09:51
No worries, always good to create new points of reference for information (I do this too when I think issues or documentation lack some good info or links to resources). Good luck with the issue on the keycastr repo, hope it can be resolved! The reason I paid for Screenflick is because I couldn't find another alternative which offered the same user experience. I think video capture and keyboard capture go hand-in-hand and keyboard capture should be present but alas, it doesn't seem to be like that often and I'd end up resorting to multiple applications. This tends to be quite clunky when recording different screen areas for a blog post :sweat_smile: 

I didn't get sponsored but if you've got $35 spare money you'd have a lifetime license of a pretty powerful and feature rich recording tool :)

**Comment by sdondley** [comment] 2020-07-20 10:53
It's not so much about me saving $35 as it is just to see if a solution can be done with open source software that others may want to try. I wish someone could figure out a good business model for having that $35 go to an open source project instead to help support their efforts.

**Comment by SidOfc** [comment] 2020-07-20 13:47
If someone would make a viable alternative which also works on linux, I'd happily donate even $70 for the cause, it is a small price to pay for major convenience imo. If you do find any such application (a video+keyboard recorder) feel free to post a link here as well!
